# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A text which describes further details on what should be done with the task'),
        ),
    ]
